---
title: "Package2"
author: "Radhika Srivastava"
date: "6/21/2018"
output: html_document
---

## The Conversion Package 


When creating my first package in R, I wanted to make a something that would make truly be useful and have adequate functionality. Over the past few weeks I have been in Cape Town, I realized that it would be useful to have a tool to convert standard units used in America, to metric units used in South Africa (and the rest of the world). So, I decided to make a R package that would do just that. 

Here is the code for the function that I used to make my package: 

```{r}
conversion <- function(type,value)
  {
  if(type=="w")
  {print("Weight Conversion")
    return(value * 0.453592)}
  else if(type=="d")
  {print("Distance Conversion")
    return(value * 0.3048)}
  else if (type=="t")
  {print("Temperature Conversion")
      return((value-32)*.5556)}
  else {
    (print("Invalid Conversion Type"))
    return (-1)
  }
}
```

This function accepts two variables, the type of measurement, either weight (w), distance (d), or temperature (t), and the value in standard units. It then returns a sting saying what type of conversion it was, and the value in metric units. Additionaly, if the type is not w, d, or t, the function will print "Invalid Conversion Type" and returning a value of -1. This function does not have too much complexity, but I hope in the future to make an R package that can have more inputs and added functionality. 

To see the full code of my R-package, click [here](https://github.com/radhikasriv/Conversion)