---
title: "My first R package"
author: "Radhika Srivastava"
date: 2018-06-14
categories: ["R"]
tags: ["R Markdown", "plot", "regression"]
---


## The Conversion Package 
This is a test. 

When creating my first package in R, I wanted to make a something that would make truly be useful and have adequate functionality. Over the past few weeks I have been in Cape Town, I realized that it would be useful to have a tool to convert standard units used in America, to metric units used in South Africa (and the rest of the world). So, I decided to make a R package that would do just that. 

Here is the code for the function that I used to make my package:

```{r}
conversion <- function(type,value)
  {
  if(type=="w")
  {print("Weight Conversion")
    return(value * 0.453592)}
  else if(type=="d")
  {print("Distance Conversion")
    return(value * 0.3048)}
  else if (type=="t")
  {print("Temperature Conversion")
      return((value-32)*.5556)}
  else {
    (print("Invalid Conversion Type"))
    return (-1)
  }
}
```

This function allows for two inputs, the first is the type of conversion, either, weight (w), distance (d), or temperature (t), and the second is the value, in standard units. If the conversion type is not w,d, or t, then the function will return Invalid Conversion Type and a value of -1.

This function was a good way to make an introductory package, because it allows for multiple inputs, but is not too difficult to implement. I hope in the future to make some more complex packages that work with large data sets as well.
